### ISSUE TITLE
PHPRedis support?

### ISSUE THREAD

**Issue by roberttolton** [swayok/alternative-laravel-cache#12]
When trying to use this package with PHPRedis:
```
'client' => 'phpredis'
```

I get the error:
```
Argument 1 passed to Cache\Adapter\Predis\PredisCachePool::__construct() must be an instance of Predis\ClientInterface, instance of Redis given, called in /vagrant/vendor/swayok/alternative-laravel-cache/src/AlternativeLaravelCache/Store/AlternativeRedisCacheStore.php on line 27
```

Does this package support using PHPRedis, and if so, what's the correct configuration?

**Comment by swayok** [comment]
Hi. I have yet to add support for `phpredis`. Currently it won't work. 
As for estimation I cannot give any date right now. Too overloaded =(

**Comment by brazenvoid** [comment]
Please add support, phpredis is the way to go considering Laravel 6 is also actively endorsing it now.

**Comment by swayok** [comment]
@brazenvoid @roberttolton - Version 5.4.10 now supports PHPRedis. Tests are ok, also tested it on dev version of my project and it seems like there are no problems.
