### ISSUE TITLE
Question - Why don't put dependencie in suggest ? 

### ISSUE THREAD

**Issue by YannikFirre** [swayok/alternative-laravel-cache#13]
Hello,

Can not we put dependencies in composer suggest (https://getcomposer.org/doc/04-schema.md#suggest ) ? 

If i use the driver file, I do not need the dependencies for redis, right ? 

Thanks a lot ;)

**Comment by swayok** [comment]
All specific cache driver packages moved to "suggest" section in 5.4.13. File-based driver also.
