### ISSUE TITLE
[Proposal] Lock support

### ISSUE THREAD

**Issue by rogervila** [swayok/alternative-laravel-cache#15]
Hello,

I use this library to be able to run tests without relying on a redis connection.

Now I am facing a situation where I have to use [atomic locks](https://laravel.com/docs/7.x/cache#atomic-locks ).

It would be nice to implement the [LockProvider](https://laravel.com/api/7.x/Illuminate/Contracts/Cache/LockProvider.html) interface on [AlternativeLaravelCache](https://github.com/swayok/alternative-laravel-cache/blob/master/src/AlternativeLaravelCache/Store/AlternativeRedisCacheStore.php#L14) and use a filesystem lock strategy to implement [Lock](https://laravel.com/api/7.x/Illuminate/Contracts/Cache/Lock.html) methods.

I can work on a PR if you find this useful.

**Comment by swayok** [comment]
@rogervila Hi. If you need this - someone will need it too. 
I'm not really understand what you actually need right now so PR would be the best way to add this functionality.

**Comment by rogervila** [comment]
Nice, I will work on it next week.

**Comment by janich** [comment]
I agree. 
This would really be helpfull to have, specially for the Redis cache store...

**Comment by rogervila** [comment]
I started a PR on Laravel but it was denied due a race condition. Once I have time I will work on it again. Then I will replicate the PR on this project to leverage the functionality

**Comment by rogervila** [comment]
Looks that lock support will be released soon. 
Let's look how the integration works.

https://twitter.com/taylorotwell/status/1326538435327270916?s=19

**Comment by swayok** [comment]
Implemented in 6.0 version. Thanks to @Malezha
