### ISSUE TITLE
Laravel scheduler breaks

### ISSUE THREAD

**Issue by janich** [swayok/alternative-laravel-cache#16]
Hi

Im using this library along with a local Redis cache.
However - After installing this library, my cron scheduler broke, so nothing is getting executed. 
All api endpoints, commands, etc works, but cron broke.

Outputting cron to a file, I discovered Laravel saying '**Skipping command (has already run on another server)**'.

Well, weird. 
Almost all our jobs are executed within the Laravel scheduler in this form:
```        
$schedule->command('job:import:something')
            ->everyMinute()
            ->withoutOverlapping()
            ->onOneServer()
            ->runInBackground()
            ->environments(['production']);
````

Digging through the scheduler and cache, I found that when using ->onOneServer(), cron puts a key into the cache store (for that moment in time it needs to be executed), and returns the value of it. 

After switching to this library, that broke because **->put()** method (and more) now returns void, and not the same as their parents within Laravel.

Effectively this causes the scheduler to die, as it doesnt get the right values back from the cache stores.

It was easily fixed, by finding all methods in the cache store that exists in Laravel cache store, and make sure they return the same values too though ...

**Comment by swayok** [comment]
Thanks for the fix. New version 5.4.12 is released.
