### ISSUE TITLE
 Class 'Cache\Adapter\Filesystem\FilesystemCachePool' not found error

### ISSUE THREAD

**Issue by tanero** [swayok/alternative-laravel-cache#20]
Today after composer update, the laravel frmework upgraded from 7.27 to 7.28. After that, the application started to give me an error exception like below,

"Class 'Cache\Adapter\Filesystem\FilesystemCachePool' not found"  error.  

when I  change the driver type from file to redis this time gives me "Class 'Cache\Adapter\Redis\RedisCachePool' not found".

Deeply inspection shows some adapters (file and redis ) removed by composer, 

` - Removing cache/redis-adapter (1.0.0)
  - Removing cache/predis-adapter (1.0.0)
  - Removing cache/filesystem-adapter (1.0.0)
  - Updating symfony/deprecation-contracts (v2.1.3 => v2.2.0): Downloading (100%)
  - Updating symfony/event-dispatcher-contracts (v2.1.3 => v2.2.0): Downloading (100%)
  - Updating symfony/service-contracts (v2.1.3 => v2.2.0): Downloading (100%)
  - Updating symfony/translation-contracts (v2.1.3 => v2.2.0): Downloading (100%)
  - Updating laravel/framework (v7.27.0 => v7.28.0): Downloading (100%)
  - Updating laravel/ui (v2.2.0 => v2.2.1): Downloading (100%)
  - Updating maatwebsite/excel (3.1.21 => 3.1.22): Downloading (100%)
  - Updating swayok/alternative-laravel-cache (5.4.12 => 5.4.13): Downloading (100%)
  - Updating yajra/laravel-datatables-oracle (v9.10.2 => v9.11.0): Downloading (100%)
  - Updating barryvdh/laravel-debugbar (v3.5.0 => v3.5.1): Downloading (100%)
  - Updating facade/ignition (2.3.6 => 2.3.7): Downloading (100%)
  - Updating phpseclib/phpseclib (2.0.28 => 2.0.29): Downloading (100%)`

**Comment by swayok** [comment]
Hi. In last update I moved all specific drivers to "suggest" section of composer.json so that everyone pics only drivers they will use.

**Comment by MicVital** [comment]
I think I found the actual solution to this problem: 
The filesystem cache driver isn't available with laravel installation. To solve this, you will to first install the driver using composer
`composer require cache/filesystem-adapter
`
Afterwards, you can then install the alternative-laravel-cache

**Comment by oureco123** [comment]
I'm having the same issue.. Am not able to publish vendor

**Comment by swayok** [comment]
@oureco123, you need to manually add specific cache driver to your composer json. Refer docs: https://github.com/swayok/alternative-laravel-cache#filesystem-support. By default there are no  specific drivers required by package to avoid unnecessary drivers being installed (requested in https://github.com/swayok/alternative-laravel-cache/issues/13).

**Comment by oureco123** [comment]
Yes sir i have done this. I tried all types of lines and tried many packages (cache/cache ; cache/filesystem-adapter etc.). I can't seem to wrap my head around this :/

Maybe this is related: I'm not sure why but when i run "`composer require cache/cache` or `composer run cache/filesystem-adapter`, they install normally and get added to composer.json. But the only problem is that i can't seem to find them in vendor/cache folder.

**Comment by swayok** [comment]
That is very strange. In my project I have next folders inside `vendor/cache`:
`adapter-common`, `hierarchical-cache`, `tag-interop` and  `redis-adapter`. 
3 installed as requirements from  `swayok/alternative-laravel-cache` package and  `redis-adapter` istalled as requirement from project's `composer.json`.
You shoud have similar setup but with filesystem driver package.
Try to remove `composer.lock` and then run `composer update` (not `install`).  Your `composer.json` should contain `cache/filesystem-adapter` and `swayok/alternative-laravel-cache` requirements. This will recreate `composer.lock` with latest versions of all packages and hopefully install missing packages. Also it might be helpful to remove `vendor` folder entirely to be sure all packages are reinstalled.

**Comment by oureco123** [comment]
I followed your instructions. But now i'm having an unrelated issue (i actually did the same instructions before and had the same issue, upon attemtping to fix it i had another issue and it's just a nightmare).

`In Application.php line 690:
                                                  
  Class 'Maatwebsite\Sidebar\SidebarServiceProvi  
  der' not found`

**Comment by swayok** [comment]
It looks like something wrong with your `composer`. Have you tried to update/reinstall it? It is quite strange that some packages are not installed and then it cannot find classes (autoloader incorrect).

**Comment by oureco123** [comment]
Okay, so for whoever is having the same issue, maybe i was the only one but here is what I did:
Whenever i tried to run `composer require xxx` it would say that a class of something was not found, and whenever i tried to run `composer require packagethatwasntfound`, i'd find yet another package that wasn't found. What i did is i kept going on and at the end i required them ALL at once. Like this: `composer require astrotomic/laravel-translatable maatwebsite/laravel-sidebar mcamara/laravel-localization cache/filesystem-adapter laravel/scout`

And it worked!

Reinstalling or down/upgrading composer did not work. But thank you for your help still @swayok
