### ISSUE TITLE
Trait 'Illuminate\Cache\HasCacheLock' not found

### ISSUE THREAD

**Issue by pravo-pro** [swayok/alternative-laravel-cache#25]
Hi, thank you for your work! 
I use laravel 7 and memcached. 
After installation, I got error Trait 'Illuminate\Cache\HasCacheLock' not found
Google says that the trait appeared in laravel 8. There are options to use on laravel 7?

**Comment by swayok** [comment]
Should be fixed by 6.1.1.
I haven't tested in Laravel 7 actually but it should work. Also memcached are not tested too - there is no memcached PHP extension for Windows. 
So you will be a beta-tester =))

**Comment by pravo-pro** [comment]
It would be great if it was possible to disable custom behavior via the env file. At the moment, to return the standard driver file, I commented out the connection line in addDriversToCacheManager.
 // $this->addFileCacheDriver($cacheManager);
or, as specified in the documentation,  via the provider, but then, you need to give your drivers other names, so that the 'file' is responsible for the standard laravel driver, or make adapter for default file driver with some name like "default"

**Comment by pravo-pro** [comment]
update work thank you
