### ISSUE TITLE
PHP 8.0 Support

### ISSUE THREAD

**Issue by ravdeepsingh22** [swayok/alternative-laravel-cache#33]
composer require swayok/alternative-laravel-cache:*
./composer.json has been updated
Running composer update swayok/alternative-laravel-cache
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - lcobucci/jwt 3.4.6 requires php ^5.6 || ^7.0 -> your php version (8.0.13) does not satisfy that requirement.
    - vonage/client 2.4.0 requires vonage/client-core ^2.0 -> satisfiable by vonage/client-core[2.9.3].
    - vonage/client-core 2.9.3 requires lcobucci/jwt ^3.4|^4.0 -> satisfiable by lcobucci/jwt[3.4.6].
    - vonage/client is locked to version 2.4.0 and an update of this package was not requested.

**Comment by swayok** [comment]
Hi. This package supports PHP 8 as stated in composer.json ( "php": "^7.2.5|^8.0") and also it does not require the package you have problem with:
- lcobucci/jwt 3.4.6 requires php ^5.6 || ^7.0 -> your php version (8.0.13) does not satisfy that requirement.
