### ISSUE TITLE
Laravel 9 support

### ISSUE THREAD

**Issue by plastique** [swayok/alternative-laravel-cache#34]
Is it expected soon or waiting for this [request](https://github.com/php-cache/cache/pull/265) ?

**Comment by swayok** [comment]
I've published release that supports Laravel 9.
Currently cannot test compatibility with Laravel 9. 
Lib will work with redis. But file based cache might not work because of issue you linked.

**Comment by Krato** [comment]
Is working with redis, but there's an error if you have this package installed and choose file cache. Flysystem has been updated.

Can you check it please?

**Comment by rhurup** [comment]
> Is working with redis, but there's an error if you have this package installed and choose file cache. Flysystem has been updated.
> 
> Can you check it please?

Agree - Have the same issue.

**Comment by gulasznikow** [comment]
@RohitM-IN Seem like updating adapter is not the only thing needed. I tried to run it with L9 and seems that this repo might need an adjustment for new League/Flysystem because Class "League\Flysystem\Adapter\Local" not found  : <

**Comment by swayok** [comment]
@gulasznikow @RohitM-IN @rhurup @plastique @Krato 
Update 6.1.5 released with full support for Laravel 9 and file-based cache. Try it and tell me if it works for you.

**Comment by plastique** [comment]
> @gulasznikow @RohitM-IN @rhurup @plastique @Krato Update 6.1.5 released with full support for Laravel 9 and file-based cache. Try it and tell me if it works for you.

Working if add to composer requirements: `swayok/cache-filesystem-adapter`

**Comment by swayok** [comment]
> > @gulasznikow @RohitM-IN @rhurup @plastique @Krato Update 6.1.5 released with full support for Laravel 9 and file-based cache. Try it and tell me if it works for you.
> 
> Working if add to composer requirements: `swayok/cache-filesystem-adapter`

Good. Updated installation docs

**Comment by prg-hussam** [comment]
Hello

i have this issue when require  swayok/cache-filesystem-adapter
Laravel 9.21
<img width="1680" alt="Screen Shot 2022-07-22 at 10 59 59 PM" src="https://user-images.githubusercontent.com/18707331/180518263-26844e84-a73f-4607-aee6-10f5bda0a8ce.png">

**Comment by swayok** [comment]
@prg-hussam It seems like some package requires `psr/cache` version which is not supported by many requried packages of this package (`cache/adapter-common` for example). And the reason is not Laravel because I currently have Laravel 9.21.6 and it installs and works normally. Check your `composer.json` if it has forced `"psr/cachce": "^3.0"` and switch it to  `"psr/cachce":"^1.0.0|^2.0.0|^3.0.0"` or just remove it. Also update `"psr/simple-cache": "^1.0.0|^2.0.0|^3.0.0"` or remove it if it is in your `composer.json`

**Comment by plastique** [comment]
> Hello
> 
> i have this issue when require swayok/cache-filesystem-adapter Laravel 9.21 <img alt="Screen Shot 2022-07-22 at 10 59 59 PM" width="1680" src="https://user-images.githubusercontent.com/18707331/180518263-26844e84-a73f-4607-aee6-10f5bda0a8ce.png">

for example my requirements (Laravel 9.21.5)

```json
"require": {
        "php": "^8.0.2",
        "ext-json": "*",
        "ext-pdo": "*",
        "artesaos/seotools": "^0.22",
        "cache/memcached-adapter": "^1.0",
        "cache/predis-adapter": "^1.0",
        "laravel/framework": "^9.0",
        "laravel/tinker": "^2.7",
        "swayok/cache-filesystem-adapter": "*",
        "swayok/alternative-laravel-cache": "^6.1.5",
        "predis/predis": "^1.1"
    },
```

**Comment by prg-hussam** [comment]
my requirements

`"require": {
        "php": "^8.0.2",
        "guzzlehttp/guzzle": "^7.2",
        "inertiajs/inertia-laravel": "^0.6.3",
        "jenssegers/agent": "^2.6",
        "laravel/fortify": "^1.13",
        "laravel/framework": "^9.21.3",
        "laravel/sanctum": "^2.14.1",
        "laravel/tinker": "^2.7",
        "mcamara/laravel-localization": "^1.7",
        "nwidart/laravel-modules": "^9.0",
        "prgayman/laravel-sidebar": "dev-master",
        "spatie/laravel-activitylog": "^4.5",
        "spatie/laravel-permission": "^5.5",
        "spatie/laravel-translatable": "^6.0",
        "tightenco/ziggy": "^1.4"
    },`

**Comment by prg-hussam** [comment]
"swayok/cache-filesystem-adapter": "*",
 
 worked ✅

**Comment by swayok** [comment]
It seems something wrong happening when you use `composer require swayok/alternative-laravel-cache` or `composer require swayok/cache-filesystem-adapter`. 
While adding these packages directly to `composer.json` and then running `composer update` works normally.

**Comment by swayok** [comment]
Ok. Solved problem with `composer require swayok/alternative-laravel-cache` by running `composer clearcache` + deleted `composer.lock` file.
