### ISSUE TITLE
Lazily initialize connection to cache

### ISSUE THREAD

**Issue by dciprian-petrisor** [swayok/alternative-laravel-cache#36]
Hello,

First off, thanks for this package! We've been making use of this at my workplace, as we also expected Laravel's tagging to work as this package makes it work and were very disappointed to discover how Laravel actually implements it.

One issue I've ran into with this package, however, is caused by a combination of https://github.com/laravel/framework/pull/34873
and the ```$this->setPrefix($prefix);``` call over here: https://github.com/swayok/alternative-laravel-cache/blob/master/AlternativeLaravelCache/Core/AlternativeCacheStore.php#L67

The ```setPrefix``` calls ```$this->getHierarchySeparator()```, which in turn calls ```$this->getWrappedConnection```, thereby instantiating the connection to the cache.

The Laravel issue linked above causes any artisan command to fully construct laravel commands, including the queue:restat command, which insantiates the cache itself:
https://github.com/laravel/framework/blob/259e0dcfd1bcdf5160ed789ee631921441e1fbe5/src/Illuminate/Foundation/Providers/ArtisanServiceProvider.php#L602-L607.

These two issues paired together make it problematic in CI for example, when running artisan commands, as the cache is instantiated, and this package attempts to connect to the cache server, which results in an error.

Laravel seems to have somewhat alleviated the issue, by allowing you to declare a static default signature in all commands starting with Laravel 9.x, but it hardly fixes the problem when adding custom commands to a Laravel project, unless you know exactly what he issue is.

To remove the problem entirely, I would like to raise a PR which fixes the issue within this package by somehow delaying the setPrefix call so that no connection is created during the constructor (haven't decided exactly how, suggestions are welcome).

Before I invest time into this, I'd like to know if you're interested in this contribution.

Thanks!

**Comment by swayok** [comment]
@dciprian-petrisor Hello. If this problem can be solved without breaking main functionality - then it is better to fix it. PR would be appreciated.

**Comment by swayok** [comment]
@dciprian-petrisor release 6.1.8 is ready. I've used your PR as base for this update (without docker files). 
But tests were failing because Hierarchical cache also works with Redis and Memcached (I've already forgot about this...) =)

**Comment by dciprian-petrisor** [comment]
@swayok good to know! I'll try the final changes in a real environment in the next few days and close the issue afterwards.

Thanks!
