### ISSUE TITLE
Laravel 10 support

### ISSUE THREAD

**Issue by bjhijmans** [swayok/alternative-laravel-cache#39]
I'm not in a particular hurry to upgrade to Laravel 10, which was released yesterday. At a glance, I expect most cache drivers to just work. However, I did spot that there were changes to Redis cache tags: https://laravel.com/docs/10.x/upgrade#redis-cache-tags.

Do those changes impact this package, and should we be running the new command when using the alternative Redis cache?

**Comment by swayok** [comment]
Hi. Changes in Laravel 10 won't affect this package because it uses independent cache libs to do the job.

**Comment by mattsches** [comment]
It may be useful to update the README where it says

```markdown
### For Laravel 5.4+

Add to `composer.json`:

    "require": {
        "swayok/alternative-laravel-cache": "5.4.*"
    }
```

to include newer `6.*` releases.

I could only install the lib in Laravel 10 after changing the version to a `6`.
