### ISSUE TITLE
Package connects with PHP-Redis (or both) at the start due to call to ->getWrappedConnection()

### ISSUE THREAD

**Issue by genesiscz** [swayok/alternative-laravel-cache#47]
[This line](https://github.com/swayok/alternative-laravel-cache/blob/cca5d418bbd2b8180e80bf7bafd4fce881d2c386/AlternativeLaravelCache/Provider/AlternativeCacheStoresServiceProvider.php#L82) tries to setLogger but what it does is also trying to connect to the redis instance. 

That is problematic for obvious reasons (phpstan that runs native while project being in Docker trying to connect every time I make a change in the code), but also unnecessary connects when it doesn't need to.

I moved the setLogger call into getWrappedConnection() and it is working flawlesly now.

**Comment by genesiscz** [comment]
THAT WAS FAST 👍  Thank you 💯 

https://github.com/swayok/alternative-laravel-cache/commit/9052a1fe6fac43683d105cb03b26c4ec11e6ace8

**Comment by swayok** [comment]
@genesiscz Fixed in [6.1.13](https://github.com/swayok/alternative-laravel-cache/tree/6.1.13).
Test it for you situation to be sure it works correctly.

**Comment by genesiscz** [comment]
Yes, it does 🥇

**Comment by genesiscz** [comment]
Fixed by https://github.com/swayok/alternative-laravel-cache/commit/9052a1fe6fac43683d105cb03b26c4ec11e6ace8

**Comment by genesiscz** [comment]
@swayok great work btw, I hated Laravel tags and love yours !
