### ISSUE TITLE
Default TTL issue: it should be a year, not 6 days

### ISSUE THREAD

**Issue by iamvladshevchuk** [swayok/alternative-laravel-cache#49]
In this commit: https://github.com/swayok/alternative-laravel-cache/commit/e3aa7c2940c524e4628966ae6127952371a76417

You changed this part of code:

```
protected function getDefaultDuration() {
   return 525600 * ($this->isDurationInSeconds() ? 60 : 1);
}
```

To this part of code:

```
protected function getDefaultDuration(): int {
    return 525600;
}
```

You said in the release:

> Removed outdated code related to Laravel <= 5.6 (cache expected minutes for ttl, since 5.7 it expects seconds);

Unfortunately, you left minutes in the `getDefaultDuration`, not seconds. It means that `forever` function in Laravel saves for 6 days (525600 seconds), not a year (525600 * 60 seconds).

The correct version would be:

 ```
protected function getDefaultDuration(): int {
    return 525600 * 60;
}
```

Or

 ```
protected function getDefaultDuration(): int {
    return 31536000;
}
```

**Comment by swayok** [comment]
Fixed in [6.1.14](https://github.com/swayok/alternative-laravel-cache/tree/6.1.14).
Thanks for report.
