### ISSUE TITLE
Possible Race Condition. Cannot delete key by tag.

### ISSUE THREAD

**Issue by iamvladshevchuk** [swayok/alternative-laravel-cache#50]
**Expected behavior**

When you create a key with a tag:
`Cache::tags('a')->rememberForever('x', fn () => 1)`

You can remove this key by tag:
`Cache::tags('a')->flush()`

**Bug**
Because of race condition, the following code: `Cache::tags('a')->flush()` sometimes won't remove the key 'x'.

**How to reproduce**
Race conditions are kinda tricky to catch. So there's chance involved. But I think I created a test to prove the problem.

I used Laravel Tinker and two terminals. In the first one I typed:
`collect(range(0,100000))->each(fn()=> Cache::tags('a')->flush())`

In the second one I typed:
`collect(range(0,100000))->each(fn()=> Cache::tags('a')->rememberForever('x', fn () => 1))`

I ran the first one and the second one as fast as I could for them to run simultaneously. We test an extreme conditions with many concurrent requests to redis.

**Expected results of the test**
I'm using Redis Commander to see the results in Redis. I expect two possible results:
1. No keys present at all. It means the `flush()` ran in the end.
2. Both tag list and a key present. It means `rememberForever()` ran in the end.

**Actual results**
Key `x` with the information is present. But tag list `a` isn't present. It means:
1. You can get the information using `Cache::get('x')`
2. But you can't remove the information using `Cache::tags('a')->flush()`. The information will be still there.

**Why it happens (possibly)**
When you add information, the code: "creates a tag list" -> "creates a key".
When you remove information, the code: "deletes a tag list" -> "deletes a key".
With race condition when there are two concurrent requests, the code sometimes inserts "remove" operation into the "add" operation: "creates a tag list" -> ("removes a tag list" -> "removes a key") -> "adds a key". Which results in no tag list, but key is present.

Does it make sense? I don't know how to fix it, but I encountered this bug and I wanted to create an issue about it.

**Comment by swayok** [comment]
This is a problem of the low-level packages where I cannot do any changes. Also it is quite expected that race conditions will happen when there are no real need for mutexes when you cache something. Usually performance is more important than reliability for such tasks. 
You can use mutexes manually to avoid this problem, but it will drop performance. Which is why this is not implemented by default. Lib solves most use cases, but not all.
