### ISSUE TITLE
Laravel 11 support

### ISSUE THREAD

**Issue by tds-dearls** [swayok/alternative-laravel-cache#51]
Laravel 11 was just released, and this is the only package that has not been updated yet.

**Comment by tds-dearls** [comment]
Here is the error I am getting. I removed the package, upgraded everything, and it updated without a problem. I pulled this package in, and here's the error:

Too few arguments to function Illuminate\Cache\CacheManager::repository(), 1 passed in (path)/vendor/swayok/alternative-laravel-cache/AlternativeLaravelCache/Provider/AlternativeCacheStoresServiceProvider.php on line 86 and exactly 2 expected

  at vendor/laravel/framework/src/Illuminate/Cache/CacheManager.php:289
@ param  \Illuminate\Contracts\Cache\Store  $store
    286▕      * @ param  array  $config
    287▕      * @ return \Illuminate\Cache\Repository
    288▕      */
  ➜ 289▕     public function repository(Store $store, array $config)
    290▕     {
    291▕         return tap(new Repository($store, Arr::only($config, ['store'])), function ($repository) {
    292▕             $this->setEventDispatcher($repository);
    293▕         });

**Comment by tds-dearls** [comment]
Here is the specific commit that adds the config parameter: https://github.com/illuminate/cache/commit/3117b68181dac2b12c405e8a0a243932dba2180b

**Comment by swayok** [comment]
Great! This will help. I think I will be able to release update today or tomorrow.

**Comment by swayok** [comment]
New version released: ([6.1.15](https://github.com/swayok/alternative-laravel-cache/releases/tag/6.1.15). 
Tests are ok, so it should work as expected.

**Comment by tds-dearls** [comment]
Thank you! Everything is downloading and no errors that I'm aware of. Should be all good!
