### ISSUE TITLE
Cache exceptions due to package or underlying libraries

### ISSUE THREAD

**Issue by geertjanknapen1** [swayok/alternative-laravel-cache#58]
On my production site, I keep running into the following exceptions. To me, it seems they're either being caused by this package or the underlying libraries, but I can't seem to figure out the actual cause.

Any pointers/solutions would be greatly appreciated.

```shell
[2024-10-11 01:56:36] prod.ALERT: foreach() argument must be of type array|object, false given {"exception":"[object] (ErrorException(code: 0): foreach() argument must be of type array|object, false given at /usr/share/nginx/html/vendor/swayok/cache-filesystem-adapter/FilesystemCachePool.php:199)
[2024-10-11 01:56:36] prod.ERROR: Exception thrown when executing "Cache\Adapter\Common\{closure}".  {"view":{"view":"/usr/share/nginx/html/resources/views/templates/partials/sliders/templates/_someview.blade.php","data":[]},"exception":"[object] (Spatie\\LaravelIgnition\\Exceptions\\ViewException(code: 0): Exception thrown when executing \"Cache\\Adapter\\Common\\{closure}\".  at /usr/share/nginx/html/vendor/cache/adapter-common/AbstractCachePool.php:338)
```

The code where the error originates, is the foreach in below snippet;
```php
protected function removeListItem($name, $key): bool
    {
        $list = $this->getList($name);
        foreach ($list as $i => $item) {
            if ($item === $key) {
                unset($list[$i]);
            }
        }

        try {
            $this->filesystem->write($this->getFilePath($name), serialize($list));
            return true;
        } catch (FilesystemException $e) {
            return false;
        }
    }
```

`$list` seems to be false in this instance, `getList()` seems to read a (cache) file and unserialize it into an array, which works sometimes (when flushing tags) but seems to go wrong at other times. But I'm unable to figure out how or when.

I'm calling the package like below, TCache is a facade around the file store;
```php
return TCache::tags([CollectionEnum::ACCESS_LIST->value, CollectionEnum::ACCESS_LIST->value . ':' . $entry->id])->remember(
            "entry_territory_restricted:{$entry->id}:{$territory->countryId()}:{$territory->stateId()}",
            config('custom.caching.ttl'),
            function () use ($entry, $territory) {
                // ... my closure
            }
        );
```

**Comment by swayok** [comment]
This seems to be a `unserialize()` failure (https://www.php.net/manual/en/function.unserialize.php). It returns `false` when fails to unserialize contents of the file. Can you check what is inside the file it fails to unserialize? It may happen that something playing tricks with your files. 
I can add a condition for this situation, but then cache might never work if serialization always fails. 
Also you MUST run `php artisan cache:clear` after each deploy to production. Serialization may fail because you have changed/removed/renamed some class that was serialized to cache. Or make sure to serialize raw data instead of models.

**Comment by geertjanknapen1** [comment]
Bit late with my update, sorry.
The problem was the cache tags I was supplying. You can't have a colon (`:`) in your cache tags.
