### ISSUE TITLE
Permission on cache folder

### ISSUE THREAD

**Issue by wimurk** [swayok/alternative-laravel-cache#9]
## The problem : 
The package stores it's cache files in the `storage/framework/cache/data/cache` folder. The `cache` folder inside the `data` folder does not have the write permissions when created. The following error occurs.

![image](https://user-images.githubusercontent.com/14072334/61774638-90d64680-adf7-11e9-82d7-322699deda44.png)

This is a serious problem on my ubuntu servers wich are auto deployed. I have to log in and set the permissions for the cache folder when i empty the cache using the `php artisan cache:clear` command.

## Solution
* When creating the `cache folder` set the permissions to be writable.
* Put the cache files inside the `storage/framework/cache/data` folder like laravel does. It don't understand why another folder is created to store the data in.

I really really like this package with the tags solution. But this is not workable if i have to set the permissions every time i deploy a new update.

**Comment by swayok** [comment]
Ok. Will try to remove that extra cache subfolder.

**Comment by wimurk** [comment]
Would it be a good idea to set the permissions using the `env` file?
Something like

```env
PERMISSIONS_DIRECTORY=0775
PERMISSIONS_FILE=0664
```

**Comment by swayok** [comment]
I think it is worse then remiving cache subfolder. Also I will investigate what permissions are used to create files and folders.

**Comment by swayok** [comment]
@wimurk I found the place where it adds additional 'cache' subfolder but there is a big problem there if I remove it - tests fail on Cache:clear() with error `League\Flysystem\RootViolationException: Root directories can not be deleted` which is not avoidable easily as I can see. 
But I found an easier solution with permissions and now you can provide file and dir permissions for `file` and `hierarchial_file` cache drivers. For details - review updated Readme.md

**Comment by wimurk** [comment]
@swayok that looks good how is the cache folder a root directory? When running `php artisan cache:clear` it removes the cache folder.

**Comment by swayok** [comment]
@wimurk If `cache` subfolder is provided - path is `/storage/framweork/cache/cache` and this folder can be deleted by `cache:clear` wihtoud problems - it deletes whole folder, not only files in it; If subfolder is not provided - path is `/storage/framweork/cache` (it is a root folder for cache files) and it throws an error because that folder should not be deleted. Actually this way it is possible to separate cache files between different site sections (frontend and admin for example). I'll add an option `subfolder` to configs to make use of this behavior.

**Comment by swayok** [comment]
You can review how it works in classes: `vendor/cache/filesystem-adapter/FilesystemCachePool.php` and `vendor/league/flysystem/src/Adapter/Local.php`. Storage path from configs passed to `vendor/league/flysystem/src/Adapter/Local.php` as `root` folder and becomes undeletable. That is why `vendor/cache/filesystem-adapter/FilesystemCachePool.php` uses `cache` subfolder to store files and safely delete that subfolder on clear.
